








const DASHBOARD_BASE_URL = '/dashboard'
const PROFILE_MENU_PREFIX = '/profile';
export const PROFILE_MENU= {
  PROFILE: DASHBOARD_BASE_URL+PROFILE_MENU_PREFIX,
  EDIT_PROFILE: DASHBOARD_BASE_URL+PROFILE_MENU_PREFIX+"/edit",
  EDUCATION_ADD: DASHBOARD_BASE_URL+PROFILE_MENU_PREFIX+"/qualification",
  WORK_EXP_ADD  : DASHBOARD_BASE_URL+PROFILE_MENU_PREFIX+"/work-history",
};

const ARTICLE_MENU_PREFIX ='/article';
export const ARTICLE_MENU= {
  ARTICLE: DASHBOARD_BASE_URL+ARTICLE_MENU_PREFIX,
  ARTICLE_DETAILS: DASHBOARD_BASE_URL+ARTICLE_MENU_PREFIX+"/slug",
};